version: 2
updates:
  - directory: "/Ktisis.Common"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
  - directory: "/Ktisis.Receiver"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
