# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "CSharpier";
    version = "0.30.2";
    hash = "sha256-MrpsVlIYyrlu3VvEPcLQRgD2lhfu8ZTN3pUZrZ9nQcA=";
  })
  (fetchNuGet {
    pname = "Macross.Json.Extensions";
    version = "3.0.0";
    hash = "sha256-nBoB4vY+R19jGPdnlN6hNmZjOeAEkOA1CS+DHLjZUJA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "8.3.0";
    hash = "sha256-LSZ91DbPswCWibHNSGWC3Jh3KQwAthVaU3r7XQJyutM=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "8.3.0";
    hash = "sha256-Hiiv10LSOMIt7KsQSsteJV4DFkLebHMYmoISn/pl2F8=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "8.3.0";
    hash = "sha256-0P14ilpV+9yp+nqZWI/ilkTnRas4pic8NjNVcYxuXWs=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "8.3.0";
    hash = "sha256-+TzBeZH2Tgs0EMoU5QuCdOD/5V8xM7MHClX578AUIxw=";
  })
  (fetchNuGet {
    pname = "Octokit.Webhooks";
    version = "2.4.1";
    hash = "sha256-FZ2Eg432VkDh8fQWXkacGJNf9Uvv5LUCAU/xrqugnFc=";
  })
  (fetchNuGet {
    pname = "Octokit.Webhooks.AspNetCore";
    version = "2.4.1";
    hash = "sha256-UGRKHb8wwtNl1nMIp2hZs0DTQZmWOAFZB8MXzbRBV7g=";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "8.3.0";
    hash = "sha256-dKBMVbKT8sf6dZPEioClYwHT/0PccwbXThUOOeCaihU=";
  })
]
