backend          = "nixos-cosmic-tfstate-beta"
branch           = "beta"
built            = true
common_project   = "drakon64-ktisis"
project          = "nixos-cosmic-beta"
region           = "europe-west2"
repository_owner = "drakon64"
tag              = "beta"
zones            = ["europe-west4-a", "europe-west4-b", "europe-west4-c"]
