name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - X64

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: drakon64-ktisis
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix-build -A docker

      - name: Set up Docker's apt repository
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Install the Docker packages
        run: sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - run: |
          sudo groupadd docker
          sudo usermod -aG docker $USER
        shell: bash

      - run: docker load < result

      - uses: google-github-actions/auth@v3
        with:
          project_id: "${{ secrets.GCP_PROJECT }}"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"

      - uses: google-github-actions/setup-gcloud@v3

      - run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Upload to Artifact Registry
        run: |
          docker tag ktisis europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ktisis/ktisis
          docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ktisis/ktisis
