name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - X64

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: drakon64-ktisis
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix-build -A docker

      - run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - run: podman load < result

      - uses: google-github-actions/auth@v3
        with:
          project_id: "${{ secrets.GCP_PROJECT }}"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"

      - uses: google-github-actions/setup-gcloud@v3

      - run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Upload to Artifact Registry
        run: |
          podman tag ktisis europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ktisis/ktisis
          podman push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ktisis/ktisis
