name: Ktisis
on:
  workflow_dispatch:

jobs:
  Docker:
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root runner" | sudo tee -a /etc/nix/nix.conf

      - uses: cachix/cachix-action@v16
        with:
          name: drakon64-ktisis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build Ktisis.Processor/docker.nix Ktisis.Receiver/docker.nix
        
      - run: cachix pin drakon64-ktisis receiver "$(nix-build Ktisis.Receiver/docker.nix)" --keep-revisions 1
        if: ${{ github.ref == 'refs/heads/main' }}
        
      - run: cachix pin drakon64-ktisis processor "$(nix-build Ktisis.Processor/docker.nix)" --keep-revisions 1
        if: ${{ github.ref == 'refs/heads/main' }}

      - run: |
          docker load < result
          docker load < result-2
          
      - run: echo "REPOSITORY_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - run: |
          docker tag ktisis-processor:1.0.0 ghcr.io/${{ env.REPOSITORY_LC }}/ktisis-processor:1.0.0
          docker tag ktisis-receiver:1.0.0 ghcr.io/${{ env.REPOSITORY_LC }}/ktisis-receiver:1.0.0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker push ghcr.io/${{ env.REPOSITORY_LC }}/ktisis-processor:1.0.0
          docker push ghcr.io/${{ env.REPOSITORY_LC }}/ktisis-receiver:1.0.0
