name: Lon

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Evaluating with current lockfile
        run: echo "CURRENT_HASH=$(nix eval --file ./default.nix docker --raw)" >> "$GITHUB_ENV"

      - name: Updating Lon lockfile
        run: nix-shell -A lon --run "lon update nixpkgs"

      - name: Evaluating with updated lockfile
        run: echo "NEW_HASH=$(nix eval --file ./default.nix docker --raw)" >> "$GITHUB_ENV"

      - name: Opening pull request
        run: |
          git checkout lon.lock
          nix-shell -A lon --run "lon bot github"
        env:
          LON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LON_LABELS: "lon,bot"
        if: ${{ env.NEW_HASH != env.CURRENT_HASH }}
