name: Lon

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: drakon64-ktisis
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Nix shell
        run: nix-shell -A lon --run "exit"

      - name: Evaluate with current lockfile
        run: echo "CURRENT_HASH=$(nix eval --file ./default.nix docker --raw)" >> "$GITHUB_ENV"

      - name: Update Lon lockfile
        run: nix-shell -A lon --run "lon update nixpkgs"

      - name: Evaluate with updated lockfile
        run: echo "NEW_HASH=$(nix-build -A docker)" >> "$GITHUB_ENV"

      - name: Open pull request
        run: |
          git checkout lon.lock
          nix-shell -A lon --run "lon bot github"
        env:
          LON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LON_LABELS: "lon,bot"
        if: ${{ env.NEW_HASH != env.CURRENT_HASH }}
